name: "Run terraform plan"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Deploy"
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
        
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Run - Terraform Init"
        run: |
          cd terraform/
          terraform init -input=false

      - name: "Run - Terraform Apply"
        run: |
          cd terraform/
          terraform apply -auto-approve -input=false -no-color